AR/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('main.urls')),
]

main/urls.py
from django.conf.urls import url

from . import views

app_name = 'main'
urlpatterns = [
	url(r'^$', views.index, name='accueil'),
	url(r'^histoire/$', views.histoire, name='histoire'),
	url(r'^contact/$', views.contact, name='contact'),
	
	url(r'^membres/$', views.Membres.as_view(), name='membres'),
	url(r'^membre/(?P<pk>[0-9]+)$', views.MembreDetail.as_view(), name='membre'),
	
	url(r'^activités/$', views.Activities.as_view(), name='activités'),
	url(r'^activité/(?P<pk>[0-9]+)$', views.ActivityDetail.as_view(), name='activité'),
	
	url(r'^bistrots/$', views.Bistrots.as_view(), name='bistrots'),
	url(r'^bistrot/(?P<pk>[0-9]+)$', views.BistrotDetail.as_view(), name='bistrot'),
]

main/models.py
from django.db import models

class Activity(models.Model):
	titre = models.CharField(max_length=128)
	description = models.TextField()
	date = models.DateTimeField()
	duration = models.DurationField(blank=True, null=True)
	lieu = models.CharField(max_length=128, blank=True, null=True)
	def __str__(self):
		return self.titre
		
class Membre(models.Model):
	nom = models.CharField(max_length=64)
	prenom = models.CharField(max_length=64)
	date_naissance = models.DateField(blank=True, null=True)
	email = models.EmailField(blank=True, null=True)
	adresse = models.CharField(max_length=128, blank=True, null=True)
	def __str__(self):
		return self.prenom + ' ' + self.nom
		
class Bistrot(models.Model):
	nom = models.CharField(max_length=64)
	adresse = models.CharField(max_length=128)
	contact = models.CharField(max_length=128, blank=True, null=True)
	description = models.TextField()
	def __str__(self):
		return self.nom

main/views.py
from django.shortcuts import render
from django.views import generic

from .models import Activity, Membre, Bistrot

def index(request):
	activities = Activity.objects.order_by('-date')[:3]
	context = {'activities': activities}
	return render(request, 'main/index.html', context)
	
def histoire(request):
	return render(request, 'main/histoire.html')
	
def contact(request):
	return render(request, 'main/contact.html')
	
class Activities(generic.ListView):
	model = Activity
	template_name = 'main/activités.html'
	context_object_name = 'activities'
	def get_queryset(self):
		return Activity.objects.order_by('-date')

class ActivityDetail(generic.DetailView):
	model = Activity
	template_name = 'main/activité.html'

class Membres(generic.ListView):
	model = Membre
	template_name = 'main/membres.html'
	context_object_name = 'membres'
	def get_queryset(self):
		return Membre.objects.order_by('-date_naissance')

class MembreDetail(generic.DetailView):
	model = Membre
	template_name = 'main/membre.html'

class Bistrots(generic.ListView):
	model = Bistrot
	template_name = 'main/bistrots.html'
	context_object_name = 'bistrots'
	def get_queryset(self):
		return Bistrot.objects.order_by('nom')

class BistrotDetail(generic.DetailView):
	model = Bistrot
	template_name = 'main/bistrot.html'

main/templates/main/activité.html
{% extends 'main/index.html' %}
{% load staticfiles %}

{% block style %}
<link rel="stylesheet" href="{% static 'main/style/activité.css' %}"/>
{% endblock %}

{% block main %}

	<h1>{{activity.titre}}</h1>
	{{activity.date}}</br>
	{{activity.description}}</br>
	{{activity.adresse}}

{% endblock %}

main/templates/main/activités.html
{% extends 'main/index.html' %}
{% load staticfiles %}

{% block style %}
<link rel="stylesheet" href="{% static 'main/style/activités.css' %}"/>
{% endblock %}

{% block main %}
<h1>Liste des activités</h1>
{% for activity in activities %}
	<a href="{% url 'main:activité' activity.id %}"><h3>{{activity.titre}}</h3></a>
	{{activity.date}}</br>
	{{activity.description}}</br>
	{{activity.adresse}}
	<hr/>
{% empty %}
{% endfor %}
{% endblock %}

main/templates/main/bistrot.html
{% extends 'main/index.html' %}
{% load staticfiles %}

{% block style %}
<link rel="stylesheet" href="{% static 'main/style/bistrot.css' %}"/>
{% endblock %}

{% block main %}

	<h1>{{bistrot}}</h1>
	{{bistrot.adresse}}</br>
	{{bistrot.contact}}</br>
	{{bistrot.description}}

{% endblock %}

main/templates/main/bistrots.html
{% extends 'main/index.html' %}
{% load staticfiles %}

{% block style %}
<link rel="stylesheet" href="{% static 'main/style/bistrots.css' %}"/>
{% endblock %}

{% block main %}
<h1>Liste des bistrots</h1>
{% for bistrot in bistrots %}
	<a href="{% url 'main:bistrot' bistrot.id %}"><h3>{{bistrot}}</h3></a>
	{{bistrot.adresse}}</br>
	{{bistrot.contact}}
	<hr/>
{% empty %}
{% endfor %}
{% endblock %}

main/templates/main/contact.html
{% extends 'main/index.html' %}
{% load staticfiles %}

{% block style %}
<link rel="stylesheet" href="{% static 'main/style/contact.css' %}"/>
{% endblock %}

{% block main %}
<a id="mailto" href="mailto:contact@plescoff.fr">Écrire un mail</a>
<div id="mail">
<p> Votre email </p>
<input type="mail"/>
<p> Message </p>
<input type="color"/>
<textarea cols="80" rows="20"></textarea>
</div>
{% endblock %}

main/templates/main/histoire.html
{% extends 'main/index.html' %}
{% load staticfiles %}

{% block style %}
<link rel="stylesheet" href="{% static 'main/style/histoire.css' %}"/>
{% endblock %}

{% block main %}
<article>
<!-- page 1 -->
<div class="left arrow"><a href="#" onclick="toogle(0)">⟨</a></div>
<div class="page1">
<p>
Curieusement l’académie Rabelais est née de la
dernière guerre et notamment, de l’occupation
allemande !</p><p>
Un certain nombre d’écrivains et de journalistes,
entre autres ceux du FIGARO étaient repliés à
LYON; très rapidement ceux-ci ont commencé à
souffrir à la fois des restrictions alimentaires et de
l’éloignement de leurs habitudes.</p><p>
La plupart d’entre eux connaissaient, ou même
étaient amis de l’écrivain Marcel GRANCHER
auteur notamment du merveilleux "Cinq de campagne"
et du célèbre "Charcutier de Machonville"
ainsi que du chroniqueur gastronomique : Henry
CLOS-JOUVE. Or ces deux compères avaient
depuis des lustres de sympathiques relations avec
tous les bistrots lyonnais, connus sous le nom de
"Bouchons".</p><p>
Leurs amis leur demandaient donc s’ils ne pouvaient
pas essayer d’organiser des dîners où faire
bonne chère et le vin permettraient d’évoquer le
bon vieux temps d’avant guerre.
Ceci se réalisa et une fois par semaine, tout un
groupe de gourmands et même mieux, de fins
Gourmets, se trouva réuni devant une table bien
garnie.</p><p>
Bien entendu, aucune association formelle ne fut
créée mais, se souvenant qu’une oeuvre caritative
s’appelait "la goutte de lait" Marcel GRANCHER
donna le nom de "la Goutte de vin" cette réunion
amicale hebdomadaire.</p><p>
Les derniers temps de l’occupation ne permettaient
plus guère ces retrouvailles entre gens qui
auraient pris et fait prendre aux autres trop de risques
étant leurs activités clandestines; les dîners
cessèrent.</p><p>
La guerre se termine enfin, beaucoup retrouvent
Paris et conservent du séjour lyonnais le souvenir
ému de ces rencontres amicales.</p><p>
Georges RAVON, journaliste au FIGARO va trouver
Marcel GRANCHER et lui demande de trouver
une idée qui permettrait à tous ces gens qui
avaient tant sympathisé de se retrouver régulièrement.
</p><p>
La première idée fut de créer une Académie
COURTELINE, mais la veuve de l’auteur
"Marie-Jeanne" en acceptait l’idée, mais à la condition 
de désigner elle même les académiciens.
Et voilà pourquoi est née le 10 Juin 1948,
L’ACADEMIE RABELAIS : il n’y avait pas de Veuve
La liste des premiers membres fut la suivante :
Maurice Sailland, dit Curnonsky - Pierre Scize -
André Berry - Julien Pavil - Yves Gandon - Kleber
Haedens - Yves Krier - Paul Gordeaux - Georges
Ravon - Raymond Souplex - J,P. Gassier - André
Warnod - Geo London - Henry Clos Jouve - Marcel
E.Grancher - Paul Vincent - Michel Herbert - Henri
Monier - Henri Jeanson - J. Sennep.</p><p>
</div>
<!-- page 2 -->
<div class="page2">
Chaque fauteuil avait le nom d’un Cru de vin
choisi par l’Académiciens en fonction de sa dilection
personnelle particulière . </p><p>
Il y eut au fil des ans pas mal de changements
aux statuts, mais l’esprit de ceux-ci est globalement
resté le même.</p><p>
A ce jour, l’Académie décerne quatre récompenses :</p>
<ol>
<li> Un prix littéraire à une oeuvre d’inspiration
rabelaisienne, ou, à tout le moins, une oeuvre
gaie et de bonne humeur. Il est doté de vingt
quatre bouteilles de Beaujolais, offertes par
l’U.I.V.B. (Union Interprofessionnelle des vins
du Beaujolais) et l'Académie Rabelais
</li><li>La Coupe du Meilleur Pot, attribuée à un Bistrot
servant au comptoir des vins de qualités,
choisis par le patron de l’établissement et, dans
la mesure du possible, mis en bouteilles par lui
. Cette Coupe est offerte au nom du Patron de
l’établissement; celui-ci peut continuer à en
faire état s’il continue d’exercer le même métier
ailleurs, mais son successeur n’y a pas droit.</li></ol>
<p>
La Coupe passe d’année en année de mains en
mains le récipiendaire conservant un diplôme,
qui devient diplôme de bronze après dix ans de
continuité, d’argent après vingt ans, d’or après
vingt cinq ans.</p>
<ol start="3"><li>Le Prix Raoul PONCHON, représenté par un
diplôme attribué à un restaurateur pour la
qualité de son accueil et sa gentillesse.</li>
<li>Un diplôme particulier est attribué à un restaurateur,
ou à un Chef, lorsque les Académiciens 
considèrent que celui-ci est mérité
par la haute qualité de sa cuisine. Il est rare car
il n’est attribué qu’à bon escient.</li></ol>
<p>Au fil des ans, il y eut, outre les Académiciens
dont le nombre passa de Vingt à trente, des
Consuls également au nombre de trente.</p><p>
Aujourd’hui, il n’y a plus que des Académiciens,
au nombre de cinquante, et
quelques Consuls stagiaires, qui attendant au
minimum un an pour devenir Académicien, ou
davantage si le nombre de Cinquante est atteint.</p>
</div>
<div class="right arrow"><a href="#" onclick="toogle(1)">⟩</a></div>
</article>
{% endblock %}

{% block script %}
<script src="{% static 'main/js/histoire.js' %}"></script>
{% endblock %}

main/templates/main/index.html
{% load staticfiles %}

<!DOCTYPE html>
<html>
<head>
	<link rel="stylesheet" href="{% static 'main/style/ar.css' %}"/>
	{% block style %}
	<link rel="stylesheet" href="{% static 'main/style/accueil.css' %}"/>
	{% endblock %}
	<title>Académie Rabelais</title>
</head>
<!--__________________________________________ -->
<body> <!-- nav main -->
<nav>
	<a href="{% url 'main:accueil' %}">
		<img src="{% static 'main/images/ar.png' %}"/></a>
	<a href="{% url 'main:accueil' %}">
		<h2>académie rabelais</h2></a>
	<ul>
	<a href="{% url 'main:histoire' %}">
		<li class="h" onmouseover="selectionner('h')" onmouseout="deselectionner('h')">histoire</li></a>
	<a href="{% url 'main:activités' %}">
		<li class="a" onmouseover="selectionner('a')" onmouseout="deselectionner('a')">activités</li></a>
	<a href="{% url 'main:bistrots' %}">
		<li class="g" onmouseover="selectionner('g')" onmouseout="deselectionner('g')">guide</li></a>
	<a href="{% url 'main:membres' %}">
		<li>membres</li></a>
	<a href="{% url 'main:contact' %}">
		<li>contact</li></a>
	</ul>
</nav>
<!--__________________________________________ -->
<main> <!-- header quote section -->
{% block main %}
<header>
	<div class="g" onmouseover="selectionner('g')" onmouseout="deselectionner('g')">
	à la une ... <br/>
	<em>Cuvée spéciale</em>
	</div>
	<div>
	<img width="256px" src="{% static 'main/images/AR.png' %}"/> <h2>académie rabelais</h2>
	</div>
	<div class="g" onmouseover="selectionner('g')" onmouseout="deselectionner('g')">
	à la une ... <br/>
	<em>Nouveauté dans le guide</em>
	</div>
</header>
<quote><q>L'appétit vient en mangeant ; la soif s'en va en buvant.</q> François Rabelais</quote>
<!--__________________________________________ -->
<section> <!-- aside article -->
<aside class="a" onmouseover="selectionner('a')" onmouseout="deselectionner('a')">
	
	{% for activity in activities %}
	<div><h3>{{activity.titre}}</h3>
	<big>{{activity.date.year}}</big></br>
	{{activity.description}}</br>
	{{activity.lieu}}
	</div><hr/>
	
	{% empty %}
	Pas d'activités
	{% endfor %}
</aside>
<!--__________________________________________ -->
<article>
	<p>Cette association a pour objet d'encourager chez ses membres et leurs amis le respect des principes du Maître François Rabelais: le rire, l'ironie, la farce, la chanson joyeuse, le bien penser, le gai savoir, et bien sûr le bien manger et le bien boire.</p>
	<hr/>
	<div class="h" onmouseover="selectionner('h')" onmouseout="deselectionner('h')">
	<p>Curieusement l’académie Rabelais est née de la dernière
	guerre et notamment, de l’occupation allemande !</p><p>
	Un certain nombre d’écrivains et de journalistes, entre autres ceux du FIGARO étaient repliés à LYON; très rapidement ceux-ci ont commencé à souffrir à la fois des restrictions alimentaires et de l’éloignement de leurs habitudes.</p><p>
	La plupart d’entre eux connaissaient, ou même étaient amis de l’écrivain Marcel GRANCHER auteur notamment du merveilleux "Cinq de campagne" et du célèbre "Charcutier de Machonville" ainsi que du chroniqueur gastronomique : Henry CLOS-JOUVE...
	<a href="{% url 'main:histoire' %}"><em>Lire la suite</em></a>
	</p>
	</div>
</article>
</section>
{% endblock %}
</main>
{% block script %}
<script src="{% static 'main/js/accueil.js' %}"></script>
{% endblock %}
</body>
</html>

main/templates/main/membre.html
{% extends 'main/index.html' %}
{% load staticfiles %}

{% block style %}
<link rel="stylesheet" href="{% static 'main/style/membre.css' %}"/>
{% endblock %}

{% block main %}

	<h1>{{membre}}</h1>
	{{membre.date_naissance}}</br>
	{{membre.email}}</br>
	{{membre.adresse}}

{% endblock %}

main/templates/main/membres.html
{% extends 'main/index.html' %}
{% load staticfiles %}

{% block style %}
<link rel="stylesheet" href="{% static 'main/style/membres.css' %}"/>
{% endblock %}

{% block main %}
<h1>Liste des membres</h1>
{% for membre in membres %}
	<a href="{% url 'main:membre' membre.id %}"><h3>{{membre}}</h3></a>
	{{membre.date_naissance}}</br>
	{{membre.email}}</br>
	{{membre.adresse}}
	<hr/>
{% empty %}
{% endfor %}
{% endblock %}